title: Saldofit Releases
description: Alle Releases und Verbesserungen von Saldofit
lang: de
theme: minima

# Releases are stored as posts: _posts/YYYY-MM-DD-name.md
permalink: /releases/:year-:month-:day/
